### ISSUE TITLE
componentWillUnmount

### ISSUE THREAD

**Issue by pwmckenna** [jungledre/react-snow-effect#8]
If I stop rendering this component, react will unmount this and the canvas element will no longer exist. However the setInterval keeps going forever trying to update. If I unmount, it would be nice if that interval was cleared. This should just require implementing componentWillUnmount and calling clearInterval...which means you'll also need to keep track of the setInterval return value somehow :)

**Comment by jungledre** [comment]
https://github.com/jungledre/react-snow-effect/blob/master/src/snow.jsx#L94-L97

**Comment by jungledre** [comment]
added! :+1:
